default:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_DEV
  EMAIL_PASSWORD: EMAIL_PASSWORD_DEV
  DBNAME: DBNAME_DEV
  DBUSER: DBUSER_DEV
  DBPASSWORD: DBPASSWORD_DEV
  DBHOST: DBHOST_DEV
  DBPORT: DBPORT_DEV
  DOMAIN: DOMAIN_DEV

dev:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_DEV
  EMAIL_PASSWORD: EMAIL_PASSWORD_DEV
  DBNAME: DBNAME_DEV
  DBUSER: DBUSER_DEV
  DBPASSWORD: DBPASSWORD_DEV
  DBHOST: DBHOST_DEV
  DBPORT: DBPORT_DEV
  DOMAIN: DOMAIN_DEV
  
prod:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_PROD
  EMAIL_PASSWORD: EMAIL_PASSWORD_PROD
  DBNAME: DBNAME_PROD
  DBUSER: DBUSER_PROD
  DBPASSWORD: DBPASSWORD_PROD
  DBHOST: DBHOST_PROD
  DBPORT: DBPORT_PROD
  DOMAIN: DOMAIN_PROD