default:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_DEV
  EMAIL_PASSWORD: EMAIL_PASSWORD_DEV

dev:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_DEV
  EMAIL_PASSWORD: EMAIL_PASSWORD_DEV
  
prod:
  SECRET_KEY: SECRET_KEY
  DEBUG: DEBUG
  EMAIL_USER: EMAIL_USER_PROD
  EMAIL_PASSWORD: EMAIL_PASSWORD_PROD