name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd YourMoneyTrackerMail/

          if [ ! -d "env" ]; then
              python3 -m venv env
          fi

          # Primero hacemos pull para asegurarnos de que tenemos la última versión
          git pull

          # Usar la ruta completa para pip
          env/bin/pip install -r requirements.txt

          # collectstatic sin interacción
          env/bin/python manage.py collectstatic --noinput

          # migrate sin interacción
          # env/bin/python src/manage.py migrate --noinput

          # sudo systemctl restart yourmoneytrackermail
